# SPDX-FileCopyrightText: 2019 ESPHome
# SPDX-FileCopyrightText: 2025 Aaron White <w531t4@gmail.com>
# SPDX-License-Identifier: MIT
esphome:
  name: matrix-display
  platformio_options:
    lib_deps:
      - https://github.com/w531t4/ESP32-FPGA-MatrixPanel#main

display:
  - platform: fpga_matrix_display
    id: matrix
    width: 64
    height: 32
    use_custom_library: true
