esphome:
  name: matrix-display
  friendly_name: Matrix Display

external_components:
  - source: github://w531t4/ESP32-FPGA-MatrixDisplayWrapper@main

esp32:
  board: esp32dev
  framework:
    type: arduino

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto
    size: 10

display:
  - platform: fpga_matrix_display
    id: matrix
    width: 64
    height: 32

    lambda: |-
      it.print(0, 0, id(roboto), "Hello World!");

switch:
  - platform: fpga_matrix_display
    matrix_id: matrix
    name: "Power"
    id: power

number:
  - platform: fpga_matrix_display
    matrix_id: matrix
    name: "Brightness"
