#!/bin/sh
# SPDX-FileCopyrightText: 2025 Aaron White <w531t4@gmail.com>
# SPDX-License-Identifier: MIT
# Stop on errors
set -e

cd "$(realpath "$(dirname "$0")/..")"

echo "Installing development dependencies..."

# Install esphome
uv pip install \
  -r requirements.txt \
  colorlog \
  --upgrade \
  --config-settings editable_mode=compat

depends_path="/home/vscode/depends"
mkdir -p ${depends_path}

# # Use this section if you need to adjust esphome sources when building.
# # If going this route, ensure you run `uv pip remove esphome`, and then python3 -m esphome (from project
# # main path
# name="esphome"
# if [ ! -d ${depends_path}/${name} ]; then
#         git clone \
#                 --depth 1 \
#                 --single-branch \
#                 --branch 2025.12.1 \
#                 --recurse-submodules \
#                 --shallow-submodules \
#                 --jobs 8 \
#                 https://github.com/esphome/${name} ${depends_path}/${name}
# fi
# ln -sfnT ${depends_path}/esphome/${name} /workspaces/ESPHome-FPGA-MatrixPanelWrapper/esphome

name="ESP32-FPGA-MatrixPanel"
if [ ! -d ${depends_path}/${name} ]; then
        git clone \
                --depth 1 \
                --single-branch \
                --branch main \
                --recurse-submodules \
                --shallow-submodules \
                --jobs 8 \
                https://github.com/w531t4/${name} ${depends_path}/${name}
fi
for each in $(ls *.hpp *.cpp | grep -v main.cpp); do
        ln -sf ${depends_path}/${name}/src/${each} /workspaces/ESPHome-FPGA-MatrixPanelWrapper/components/fpga_matrix_display/${each}
done

depends_path="/home/vscode/depends"
name="ESPHome-core_load"
if [ ! -d ${depends_path}/${name} ]; then
        git clone \
                --depth 1 \
                --single-branch \
                --branch main \
                --recurse-submodules \
                --shallow-submodules \
                --jobs 8 \
                https://github.com/w531t4/${name} ${depends_path}/${name}
fi
ln -sfnT ${depends_path}/${name}/components/core_load /workspaces/ESPHome-FPGA-MatrixPanelWrapper/components/core_load

.devcontainer/bootstrap-private-configs
